#!/usr/bin/env bash
# Prints "Best School" 10 times; prints "Hi" after 9th iteration

count=1
while [ $count -le 10 ]; do
  echo "Best School"
  if [ $count -eq 9 ]; then
    echo "Hi"
  fi
  ((count++))
done
