#!/usr/bin/env bash
# List files in current directory; if filename has a dash (-), print part after first dash, else print whole filename

for file in *; do
  if [[ "$file" == *-* ]]; then
    echo "${file#*-}"
  else
    echo "$file"
  fi
done
